!!python/object/new:openpoints.utils.config.EasyConfig
dictitems:
  batch_size: 32
  ckpt_dir: log/scanobjectnn/scanobjectnn-train-pan-ngpus1-seed1174-20250506-144155-7T4oXRtkNC7Ls8dxRSe7Mu/checkpoint
  criterion_args: !!python/object/new:openpoints.utils.config.EasyConfig
    dictitems:
      NAME: SmoothCrossEntropy
      label_smoothing: 0.3
  dataloader: !!python/object/new:openpoints.utils.config.EasyConfig
    dictitems:
      num_workers: 6
  dataset: !!python/object/new:openpoints.utils.config.EasyConfig
    dictitems:
      common: !!python/object/new:openpoints.utils.config.EasyConfig
        dictitems:
          NAME: ScanObjectNNHardest
          data_dir: ./data/ScanObjectNN/h5_files/main_split
      train: !!python/object/new:openpoints.utils.config.EasyConfig
        dictitems:
          split: train
      val: !!python/object/new:openpoints.utils.config.EasyConfig
        dictitems:
          num_points: 1024
          split: val
  datatransforms: !!python/object/new:openpoints.utils.config.EasyConfig
    dictitems:
      kwargs: !!python/object/new:openpoints.utils.config.EasyConfig
        dictitems:
          angle:
          - 0.0
          - 1.0
          - 0.0
          gravity_dim: 1
          scale:
          - 0.9
          - 1.1
      train:
      - PointsToTensor
      - PointCloudScaling
      - PointCloudCenterAndNormalize
      - PointCloudRotation
      val:
      - PointsToTensor
      - PointCloudCenterAndNormalize
      vote:
      - PointCloudRotation
  deterministic: false
  dist_backend: nccl
  dist_url: tcp://localhost:8888
  distributed: false
  epoch: 0
  epochs: 250
  exp_dir: log/scanobjectnn/scanobjectnn-train-pan-ngpus1-seed1174-20250506-144155-7T4oXRtkNC7Ls8dxRSe7Mu
  exp_name: pan
  feature_keys: pos
  finetune: false
  grad_norm_clip: 10
  ignore_index: null
  launcher: mp
  layer_decay: 0
  load_path: null
  local_rank: 0
  log_dir: log/scanobjectnn/scanobjectnn-train-pan-ngpus1-seed1174-20250506-144155-7T4oXRtkNC7Ls8dxRSe7Mu
  log_path: log/scanobjectnn/scanobjectnn-train-pan-ngpus1-seed1174-20250506-144155-7T4oXRtkNC7Ls8dxRSe7Mu/scanobjectnn-train-pan-ngpus1-seed1174-20250506-144155-7T4oXRtkNC7Ls8dxRSe7Mu.log
  logname: null
  lr: 0.002
  min_lr: 0.0001
  mode: train
  model: !!python/object/new:openpoints.utils.config.EasyConfig
    dictitems:
      NAME: BaseCls
      cls_args: !!python/object/new:openpoints.utils.config.EasyConfig
        dictitems:
          NAME: ClsHead
          mlps:
          - 512
          - 256
          norm_args: !!python/object/new:openpoints.utils.config.EasyConfig
            dictitems:
              norm: bn1d
          num_classes: 15
      encoder_args: !!python/object/new:openpoints.utils.config.EasyConfig
        dictitems:
          NAME: PointAnchorEncoder
          feature_expansion:
          - 2
          - 2
          - 2
          - 2
          in_channels: 4
          nsamples: 24
          stride:
          - 2
          - 2
          - 2
          - 2
          width: 64
  mp: false
  multiprocessing_distributed: false
  ngpus_per_node: 1
  num_classes: 15
  num_points: 1024
  optimizer: !!python/object/new:openpoints.utils.config.EasyConfig
    dictitems:
      NAME: adamw
      weight_decay: 0.05
  opts: ''
  pretrained_path: null
  print_freq: 10
  rank: 0
  resume: false
  root_dir: log/scanobjectnn
  run_dir: log/scanobjectnn/scanobjectnn-train-pan-ngpus1-seed1174-20250506-144155-7T4oXRtkNC7Ls8dxRSe7Mu
  run_name: scanobjectnn-train-pan-ngpus1-seed1174-20250506-144155-7T4oXRtkNC7Ls8dxRSe7Mu
  save_freq: -1
  sched: cosine
  sched_on_epoch: true
  seed: 1174
  start_epoch: 1
  step_per_update: 1
  sync_bn: false
  t_max: 200
  task_name: scanobjectnn
  test: false
  use_amp: false
  use_gpu: true
  use_mask: false
  use_voting: false
  val_batch_size: 64
  val_fn: validate
  val_freq: 1
  wandb: !!python/object/new:openpoints.utils.config.EasyConfig
    dictitems:
      project: PointNeXt-ScanObjectNN
      tags:
      - scanobjectnn
      - train
      - pan
      - ngpus1
      - seed1174
      use_wandb: false
  warmup_epochs: 0
  world_size: 1
